### ISSUE TITLE
Map containerized jupyter server to random host port

### ISSUE THREAD

**Issue by cisaacstern** [catalyst-cooperative/pudl-examples#1]
https://twitter.com/CatalystCoop/status/1367898228549505027?s=20

The above tweet raises the question of how to achieve the aim identified in the title of this issue.

By changing the `ports` section of `docker-compose.yml` to the following:
```
ports:
      - ${PUDL_JUPYTERLAB_PORT}
```
... calling `docker-compose up` will then map the container to a random host port.

Post-build, the random port can be identified with `docker-compose ps`, which will have an output something like this:
```
     Name                    Command               State            Ports         
----------------------------------------------------------------------------------
pudl_jupyterlab   /usr/local/bin/repo2docker ...   Up      0.0.0.0:32768->8888/tcp
```
In the example above, the container is mapped to host port 32768.

To get a url for accessing the running container, run `docker-compose logs`, and look for the output reading something like:

```
pudl_jupyterlab    |     To access the server, open this file in a browser:
pudl_jupyterlab    |         file:///home/jovyan/.local/share/jupyter/runtime/jpserver-1-open.html
pudl_jupyterlab    |     Or copy and paste one of these URLs:
pudl_jupyterlab    |         http://60d3c66323b2:8888/lab?token=7355123524a0642c390272824ca15c5319bf185ddeda173e
pudl_jupyterlab    |      or http://127.0.0.1:8888/lab?token=7355123524a0642c390272824ca15c5319bf185ddeda173e
```

Use the last of the three urls, but replace 8888 with the randomly selected port (identified above by `docker-compose ps`). Following our current example, then the container can be accessed at the following url:
```
http://127.0.0.1:32768/lab?token=7355123524a0642c390272824ca15c5319bf185ddeda173e
```
(Note here that 8888 was replaced with 32768.)

**Comment by cisaacstern** [comment]
If this random port assignment feature is only needed for a minority of users who already have port 8888 occupied with another jupyter server, it might be worth considering implementing this feature via a secondary docker-compose file, which could be titled something like, `docker-compose.randport.yml`.

Then, users who want to run the container on a random port, can build the container with:
```
docker-compose --file docker-compose.randport.yml up
```
This saves "average" users (who are able to run on default port 8888) the trouble of needing to identify the random port and tokenized url via `docker-compose ps` and `docker-compose logs`.

**Comment by zaneselvans** [comment]
For our users to be able to manage this, I think we need to have the correct URL printed out for them when they run `docker-compose up`. Asking them to run `docker-compose ps` and reconstruct the URL using the randomly selected port would be very confusing (especially since it's in direct conflict with the message that's showing up in the logs). Many of them have no familiarity with the command line or Docker and are just starting to dip their toes into Jupyter Notebooks, coming mostly from spreadsheet-based analysis.  So either we need to hide the logging output and replace it with some other output, or we need to re-write it, or we need to arrange to have it happen to say the right thing... even though it's referring to the situation inside the container and not the host machine -- like if it were running on the same random port internally and externally, the URL would happen to be correct. The hard-coded probably-not-in-use port would also work in most cases here I guess.

**Comment by zaneselvans** [comment]
I went ahead and set it up to use a randomly selected port -- the same randomly selected port every time.  So at least it's not going to collide with the standard 8888, and we can hard-code that port number in the documentation and it'll be correct.
